avatar: https://img.0a0.moe/od/01tklsjzdclem6s7tmfzczilh5oktcpyji # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
    path: https://img.0a0.moe/od/01tklsjzfwjkirxxtttrhj77jylk77wrrj
    width: 2000
    height: 1260
favicon:
    href: https://img.0a0.moe/od/01tklsjzhkysc76bfzi5d3bt2qphxw5iaf # 网站图标
    type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# 附加图标库 使用说明：https://hexo.kira.host/config/icon.html
iconlib: //at.alicdn.com/t/c/font_2602317_ka2kswzg98j.css

cdn:
    waline:
        css: https://registry.npmmirror.com/@waline/client/v3/files/dist/waline.css
        js: https://registry.npmmirror.com/@waline/client/v3/files/dist/waline.js

# beian: 赣ICP备2021007955号-3 # 备案号（选填）

menu:
    回到首页:
        - /
        - icon-home
    文章归档:
        - /archive
        - icon-container
    关于本人:
        - /about
        - icon-user
    我的朋友:
        - /friends
        - icon-team

widgets:
    - social
    - category
    - tagcloud
    - archive

maxTagcloud: 10 # 标签云组件显示的标签数量，0 表示不限制

social:
    X:
        - https://x.com/lrhtony
        - icon-x-social-media
        - rgb(25, 23, 23)
        - rgba(25, 23, 23, .15)
    Bilibili:
        - https://space.bilibili.com/234060455
        - icon-bilibili
        - rgb(231, 106, 141)
        - rgba(231, 106, 141, .15)
    GitHub:
        - https://github.com/lrhtony/
        - icon-github
        - rgb(25, 23, 23)
        - rgba(25, 23, 23, .15)
    Mail:
        - mailto:lrhtony@lrhtony.cn
        - icon-email
        - rgb(102, 204, 255)
        - rgba(102, 204, 255, .15)

color: # 配色方案，从first到seventh为优先级为1-7的颜色，默认为彩虹配色
    first: # 同时作为主题色
        r: 49
        g: 174
        b: 255
    second:
        r: 255
        g: 78
        b: 106
    third:
        r: 255
        g: 185
        b: 0
    fourth:
        r: 51
        g: 213
        b: 122
    fifth:
        r: 0
        g: 219
        b: 255
    sixth:
        r: 255
        g: 69
        b: 0
    seventh:
        r: 144
        g: 144
        b: 255

# 评论区
waline:
    active: true # 是否启用 waline
    serverURL: https://waline.api.lrhtony.cn # 服务器地址
    emojis:
        - //emoji.shojo.cn/bili/webp/tv_小电视
        - //emoji.shojo.cn/bili/webp/蜜汁工坊（充电）
    wordLimit: 2048
    recaptchaV3Key: 6Lcwc9gZAAAAAODTjeHy50qAAoqfoxy5WNBXAk5U

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank">CC BY-NC-SA 4.0</a> 协议进行许可'

# 自定义侧边栏尾部内容
sidebar: ''

# 自定义样式
# customStyles:
#     - style
#     - custom

# 友链配置
friends:
    # - avatar: <友链缩略图>
    #   link: <跳转连接>
    #   name: <名称>
    #   description: <描述>
    A&D工作室:
        - name: Phrinky
          link: https://blog.rkk.moe/
          avatar: https://gravatar.shojo.cn/avatar/28069568a8b1f77c411f61904d18884e3c2fc5fdd330da0092b66db1170c9cf7?size=512
          description: 可爱 技术超强

    朋友:
        - name: CDM258
          link: http://cdm258.tech/
          avatar: https://gravatar.shojo.cn/avatar/cdc1b1ffd4c68f546ebde3ab56ef34e7f1bf6a9b426527a9112cf4c816ec30de?size=512
          description: Think what Ichiro would do

# 可复制的代码块
copyableCodeblock: true